version: 0.2

env:
  shell: bash
  variables:
    STAGE: "dev"


phases:
  install:
    commands:
      - echo installing packages
      - virtualenv venv
      - source venv/bin/activate
      - pip install -r requirements.txt
  pre_build:
    commands:
      - echo pre build phase start
      - if [ ! -v STAGE ]; then echo stage not set; exit 1; fi
      
      # - zappa manage --no-color $STAGE "collectstatic --noinput"
  build:
    commands:
      - echo updating server with new code
      - zappa deploy $STAGE
  post_build:
    commands:
      - echo UPDATE RESULT
      - echo $CODEBUILD_BUILD_SUCCEEDING
      - if [ $CODEBUILD_BUILD_SUCCEEDING = 0 ]; then zappa rollback $STAGE -n 1; exit 1; fi