version: 0.2

phases:
  install:
    commands:
      - echo VIRTUAL ENVIRONMENT & PACKAGE INSTALLATION
      - virtualenv venv
      - source venv/bin/activate
      - pip install -r requirements.txt
  pre_build:
    commands:
      - echo PRE Build start
      - if [ ! -v STAGE ]; then echo stage not set; exit 1; fi
      - zappa manage --no-color $STAGE "collectstatic --noinput"
  build:
    commands:
      - echo UPDATING WITH NEW CODE
      - zappa update --disable_progress $STAGE
  post_build:
    commands:
      - echo UPDATE RESULT
      - if [ $CODEBUILD_BUILD_SUCCEEDING = 0 ]; then zappa rollback $STAGE -n 1; exit 1; fi